apiVersion: v1
kind: ReplicationController
metadata: 
  name: rc-1
spec:
  replicas: 3
  template:
    metadata:
      name: textchess
      labels:
        app: textchess
    spec:
      containers:
      - name: textchess
        image: iem22/textchess:version_1
  selector:
    app: textchess