IMAGE_NAME = "bento/ubuntu-20.04"
N = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 3072
        v.cpus = 2
    end
      
    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "k8s-master"
        # master.vm.synced_folder ".", "/home/vagrant/"
        master.vm.provision "shell",
            inline: "bash <(wget -qO- https://raw.githubusercontent.com/kausgang/Kubernetes-Template/main/VAGRANT-auto-setup-WINDOWS/setup-master.sh)"
            # inline: "/home/vagrant/setup-master.sh"
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "shell",
            inline: "bash <(wget -qO- https://raw.githubusercontent.com/kausgang/Kubernetes-Template/main/VAGRANT-auto-setup-WINDOWS/setup-worker.sh)"
        end
    end
  
end
