IMAGE_NAME = "bento/ubuntu-20.04"
N = 1

Vagrant.configure("2") do |config|
    # config.ssh.insert_key = false

    config.vm.provision "shell", path: "bootstrap.sh"

    # config.vm.provider "virtualbox" do |v|
    #     v.memory = 3072
    #     v.cpus = 2
    # end
      
    config.vm.define "master" do |master|

        master.vm.provider "virtualbox" do |v|
            v.name    = "master"
            v.memory = 3072
            v.cpus = 2
        end

        master.vm.box = IMAGE_NAME

        master.vm.box_check_update  = false
        master.vm.hostname = "master"
        
        # master.vm.network "private_network", ip: "172.16.16.100"
        master.vm.network "public_network", ip: "192.168.1.100"

        master.vm.synced_folder ".", "/vagrant_data"

        master.vm.provision "shell",
            # inline: "bash <(wget -qO- https://raw.githubusercontent.com/kausgang/Kubernetes-Template/main/VAGRANT-auto-setup-WINDOWS/setup-master.sh)"
            path: "setup-master.sh"
            
    end

    (1..N).each do |i|
        config.vm.define "worker-#{i}" do |node|

            node.vm.provider "virtualbox" do |v|
                v.name    = "worker-#{i}"
                v.memory = 3072
                v.cpus = 2
            end
            
            node.vm.box = IMAGE_NAME
            node.vm.box_check_update  = false

            # node.vm.network "private_network", ip: "172.16.16.10#{i}"
            node.vm.network "public_network", ip: "192.168.1.10#{i}"
            node.vm.hostname = "worker-#{i}"
            node.vm.synced_folder ".", "/vagrant_data"
            node.vm.provision "shell",
            # inline: "bash <(wget -qO- https://raw.githubusercontent.com/kausgang/Kubernetes-Template/main/VAGRANT-auto-setup-WINDOWS/setup-worker.sh)"
                path: "setup-worker.sh"

            
        end
    end
  
end
